### ISSUE TITLE
SmartArrayB110i

### ISSUE THREAD

**Issue by robertogambelli** [asand3r/zbx-hpsmartarray#1]
I tried the script on HP proliant ML310 with SmartArrayB110i integrated. 
I receive no data for ld and pd
I use SSACLI Version: 2.65.7.0 2017-02-14

here's the output of the script 

PS C:\Windows\System32\WindowsPowerShell\v1.0> C:\zabbix\bin\win64\Zbx-HPSmartAr
ray.ps1 -action lld -part ld
{"data":[{"{#LD.NUM}":"","{#LD.RAID}":"","{#LD.CAPACITY}":"","{#CTRL.SN}":"Smart
ArrayB110iSATARAIDinSlot0Embedded"}]}
PS C:\Windows\System32\WindowsPowerShell\v1.0> C:\zabbix\bin\win64\Zbx-HPSmartAr
ray.ps1 -action lld -part pd
{"data":[{"{#PD.NUM}":"","{#CTRL.SN}":"SmartArrayB110iSATARAIDinSlot0Embedded"}]
}

----------------------------------------------------------------------------------------------------------

Output of ssacli commands : 

=> ctrl slot=0 pd all show

Smart Array B110i SATA RAID in Slot 0 (Embedded)

   Array A

      physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SATA HDD, 250 GB, OK)
      physicaldrive 2I:1:2 (port 2I:box 1:bay 2, SATA HDD, 500 GB, OK)

=> ctrl slot=0 ld 1 show status

   logicaldrive 1 (232.9 GB, RAID 1): OK

=> version

   SSACLI Version: 2.65.7.0 2017-02-14
   SOULAPI Version: 2.65.7.0 2017-02-14

=> ctrl all show

Smart Array B110i SATA RAID in Slot 0 (Embedded)

--------------------------------------------------------------------

Script logs ( and Zabbix notifications )

. Smart Array Controller Battery status ((FIRENZELAVORI:hp.smartarray.health[health,SmartArrayB110iSATARAIDinSlot0Embedded,ctrl,batt]): cannot index a null matrix.
In C:\zabbix\bin\win64\Zbx-HPSmartArray.ps1:130 car:41
+         "batt" {Write-Host ($ctrlStatus[ <<<< 2] -replace ".+:\s")}
    + CategoryInfo          : InvalidOperation: (2:Int32) [], Runtim

SAME ERROR FOR MAIN AND CACHE

Smart Array Controller Main status  (FIRENZELAVORI:hp.smartarray.health[health,SmartArrayB110iSATARAIDinSlot0Embedded,pd,]): C:\zabbix\bin\win64\Zbx-HPSmartArray.ps1 : missing argument for parameter 'identity'. Specify a system.string parameter and retry 

SAME ERROR FOR LOGICAL DISKS

**Comment by asand3r** [comment]
@robertogambelli So, "ctrl all show" doesnt show controller serial number, right? Just model and slot, where it installed.

**Comment by asand3r** [comment]
OK, v0.3 has just been released, so you can check it.
https://github.com/asand3r/zbx-hpsmartarray/releases/tag/v0.3
