### ISSUE TITLE
LLD for physical devices does not pick up spares due to regex

### ISSUE THREAD

**Issue by rozniak** [asand3r/zbx-hpsmartarray#11]
Hey,

I found a problem with the LLD portion of the script that detects physical drives - I noticed that one of the disks in an array I'm monitoring doesn't show up in Zabbix.

I found the problem lies in the regex for pulling the drive info out of the CLI tool, particularly here is the output of the CLI on my affected system:

C:\Program Files\hp\hpssacli\bin>hpssacli.exe ctrl slot=0 pd all show status

   physicaldrive 1I:2:1 (port 1I:box 2:bay 1, 1 TB): OK
   physicaldrive 1I:2:2 (port 1I:box 2:bay 2, 1 TB): OK
   physicaldrive 1I:2:3 (port 1I:box 2:bay 3, 1 TB): OK
   physicaldrive 1I:2:4 (port 1I:box 2:bay 4, 1 TB): OK
   physicaldrive 2I:2:5 (port 2I:box 2:bay 5, 1 TB, spare): OK

That last drive isn't detected because of the ", spare"  bit, I have been able to solve the regex issue in my fork - the commit is here: https://github.com/rozniak/zbx-hpsmartarray/commit/604b1060a7aa90fb06a1f9083fd452b8d79b8431

I hope this helps! :+1:

**Comment by asand3r** [comment]
Hi, @rozniak 
Thank you for report. Yeap, I've got it and will correct regular expression to support spare drives as soon as posible. =)
