### ISSUE TITLE
Не мониторятся логические диски.

### ISSUE THREAD

**Issue by Kleusov** [asand3r/zbx-hpsmartarray#4]
Добрый день.

Не мониторятся логические диски.
Жду версию с выводом отладочных сообщений

**Comment by asand3r** [comment]
Привет @Kleusov. Ниже архив с версией скрипта, которая при запросе LLD для логических дисков дает примерно следующий вывод:
```bash
[asand3r@zabbix ~]# zabbix_get -s server -k 'hp.smartarray.debug[lld,ld]'
Raw ssacli.exe output:
 --- 
   logicaldrive 1 (279.4 GB, RAID 1): OK 
 --- 
Starting foreach
Current LD:    logicaldrive 1 (279.4 GB, RAID 1): OK
{"data":[{"{#CTRL.MODEL}":"Smart Array P440ar","{#LD.RAID}":"RAID 1","{#CTRL.SLOT}":"0","{#LD.CAPACITY}":"279.4 GB","{#LD.NUM}":"1","{#CTRL.SN}":"PDNLH0BRH86ACY"}]}
```
Запустите у себя её локально на сервере в консоли PowerShell:
```powershell
C:\> .\zbx-hpsmartarray_v0.5d.ps1 lld ld
```
И через zabbix_get, как показано выше. Вывод скиньте сюда, пожалуйста.
P.S. Естественно, оно не пригодно для использования в работе.
[zbx-hpsmartarray_v0.5d.zip](https://github.com/asand3r/zbx-hpsmartarray/files/2656185/zbx-hpsmartarray_v0.5d.zip)

**Comment by Kleusov** [comment]
Добрый день.

У меня нет ни ssacli.exe, ни hpacucli.exe.

Есть hpssacli.exe.

Можно его использовать ?

**Comment by asand3r** [comment]
@Kleusov 
Не могу сказать, не использовал. Лучше установить HP SmartStorage Administrator всё-таки.

**Comment by asand3r** [comment]
zabbix_get -s SERVER -k 'hp.smartarray[lld,ld]'

**Comment by asand3r** [comment]
Плюс ко всему, мне нужно увидеть как выглядит вывод ssacli.exe в консоль со следующими параметрами:
```code
ssacli.exe ctrl slot=0 ld all show status
```
Номер слота может не совпадать.

**Comment by Kleusov** [comment]
Спасибо.

Всё работает.
